config/breadcrumbs.yml:
  class: sfSimpleYamlConfigHandler
  param:
    prefix: ice_breadcrumbs_

config/seo_1.yml:
  class: sfSimpleYamlConfigHandler
config/seo_2.yml:
  class: sfSimpleYamlConfigHandler

#modules/*/config/breadcrumbs.yml:
#  class: sfDefineEnvironmentConfigHandler
#  param:
#    prefix: ice_breadcrumbs_
